name: Pull Request
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:    
    types: [opened, synchronize, reopened]

jobs:
  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.2

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: laravel
          MYSQL_DATABASE: tests
          MYSQL_USER: laravel
          MYSQL_PASSWORD: laravel
          MYSQL_TCP_PORT: 3307
        ports:
          - 3307:3307
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:      
      - name: Checkout the application
        uses: actions/checkout@v3
        with:
          fetch-depth: 1    

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpunit
          extensions: |
            gd, json, mbstring, mysql, dom, fileinfo, xml, xsl, zip, curl, bcmath, intl
          coverage: xdebug

      - name: Install composer for php
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist        

      - name: Directory Permissions
        run: |
          chmod -R 7777 storage bootstrap/cache

      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate          
          
      - name: Migrations
        run: php artisan migrate

      - name: Prepare Laravel Passport
        run: php artisan passport:keys

      - name: Unit test        
        run: composer coverage
