name: Release
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      deployments: write
      actions: write
      checks: write
      statuses: write
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: "lts/*"      

      - name: Install dependencies
        run: npm install

      - name: Generate release
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: npx semantic-release
